# Generated by Django 5.0.4 on 2024-05-22 08:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_productranking'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productranking',
            name='ranking',
        ),
    ]
