# Generated by Django 5.0.4 on 2024-05-22 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_remove_productranking_ranking'),
    ]

    operations = [
        migrations.AddField(
            model_name='productranking',
            name='ranking',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
