# Generated by Django 5.0.4 on 2024-05-22 08:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_productranking_ranking'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='productranking',
            unique_together={('product', 'ranking')},
        ),
    ]
