# Generated by Django 5.0.4 on 2024-05-22 08:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_alter_productranking_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='productranking',
            unique_together={('id', 'ranking')},
        ),
    ]
