# Generated by Django 5.0.4 on 2024-05-22 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0011_alter_productranking_ranking'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productranking',
            name='ranking',
            field=models.PositiveIntegerField(),
        ),
    ]
