# Generated by Django 5.0.1 on 2024-01-25 17:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0013_alter_customer_birth_date'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'permissions': [('cansel_order', 'Can cansel order')]},
        ),
    ]
