# Generated by Django 5.0.4 on 2024-05-22 11:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0014_alter_productranking_ranking'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productranking',
            name='product',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='rankings', to='store.product'),
        ),
    ]
