# Generated by Django 5.0.4 on 2024-05-22 13:15

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0016_alter_productranking_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productranking',
            name='ranking',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
        ),
    ]
