# Generated by Django 5.0.4 on 2024-05-22 13:25

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0017_alter_productranking_ranking'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productranking',
            name='ranking',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
        ),
    ]
