# Generated by Django 5.0.1 on 2024-01-31 20:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0017_alter_orderitem_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='address',
            name='city',
        ),
        migrations.RemoveField(
            model_name='address',
            name='street',
        ),
    ]
