# Generated by Django 5.0.4 on 2024-05-22 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0018_alter_productranking_ranking'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productranking',
            name='ranking',
            field=models.IntegerField(choices=[(1, 'Ranking 1'), (2, 'Ranking 2'), (3, 'Ranking 3'), (4, 'Ranking 4'), (5, 'Ranking 5')]),
        ),
    ]
