# Generated by Django 5.0.4 on 2024-05-22 15:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0019_alter_productranking_ranking'),
    ]

    operations = [
        migrations.AddField(
            model_name='productranking',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='store.customer'),
            preserve_default=False,
        ),
    ]
